server:
  port: 9888
spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "PUT, POST, GET, OPTIONS, DELETE"
            allowedHeaders: "Content-type, Authorization"
            maxAge: 3600
      routes:
        - id: api
          uri: lb://API-SERVER
          predicates:
            - Path=/api/**
        - id: admin
          uri: lb://ADMIN-SERVER
          predicates:
            - Path=/admin/**
        - id: file
          uri: lb://FILE-SERVER
          predicates:
            - Path=/file/**
        - id: user
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**

