server:
  port: ${user.port}
#配置数据源
spring:
  application:
    name: ${user.name}
  servlet:
    #上传文件限制
    multipart:
      #单个文件大小
      max-file-size: 20MB
      #设置总上传的数据大小
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    #数据库索引
    database: 0
    host: ${redis.url}
    port: ${redis.port}
    #    password: ${redis.password}
    #连接超时时间
    timeout: 5000
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ${db.cloud.driver-class-name}
      username: ${db.cloud.username}
      password: ${db.cloud.password}
      url: ${db.cloud.url.cloud}
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        allow: ""
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      select-strategy: not_empty
      update-strategy: not_empty
