oauth.port: 8555
oauth.name: AUTH-SERVER

sys.port: 8666
sys.name: SYS-SERVER

file.port: 8200
file.name: FILE-SERVER

api.port: 8100
api.name: API-SERVER

user.port: 8700
user.name: USER-SERVER

gateway.port: 8999
gateway.name: GATEWAY-SERVER

redis.url: 127.0.0.1
redis.port: 6379
redis.password:

#数据库源配置
db:
  cloud:
    username: root
    password: Dk2019!23456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      cloud: jdbc:mysql://47.107.148.253:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000

#线程池配置
task:
  pool:
    # 是否启用线程池
    enable: true
    # 核心线程池大小
    core-pool-size: 5
    # 最大线程数
    max-pool-size: 15
    # 队列容量
    queue-capacity: 20
    # 活跃时间
    keep-alive-seconds: 30

