server:
  port: 8800
spring:
  application:
    name: EUREKA-SERVER
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    preter-ip-address : true
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8000/eureka ；多个地址可使用,分隔
    service-url:
      defaultZone: http://admin:123456@localhost:8800/eureka/