server:
  port: 8800
spring:
  application:
    name: EUREKA-SERVER
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    #设置使用IP注册就会优先使用IP，hostname则无效
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    # 关闭自我保护机制（程序停掉了还注册的问题）
    enable-self-preservation: false
    # 主动检测失效间隔,配置成3秒,默认60000
    eviction-interval-timer-in-ms: 3000
    # 禁用use-read-only-response-cache只读缓存或者减少response-cache-update-interval-ms更新缓存的时间间隔都可以更快的同步实例信息
    #    use-read-only-response-cache: false
    # 减少readWrite 和 readOnly 同步时间间隔。
    response-cache-update-interval-ms: 3000
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://127.0.0.1:8000/eureka ；多个地址可使用,分隔
    service-url:
      defaultZone: http://admin:GXfy2021@127.0.0.1:8800/eureka/
