server:
  port: 8500
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native  # 配置使用本地储存
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties # 搜索src/main/resource 下的properties文件夹下的文件
#        git:
#          uri: https://repo.dakatech.cn/repository/projectData.git #配置git仓库的地址
#          username: admin@dakatech.cn
#          password: Dk2019123456
#          search-paths: config-files  #配置git仓库下的相对地址，可以配置多个，用 , 分割
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8800/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

#Spring Cloud Config也提供本地存储配置的方式。
#我们只需要设置属性spring.profiles.active: native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
#也可以通过spring.cloud.config.server.native.searchLocations: file:E:/properties/属性来指定配置文件的位置。
#虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。

